Update recon.yml

diff --git a/.github/workflows/recon.yml b/.github/workflows/recon.yml
--- a/.github/workflows/recon.yml
+++ b/.github/workflows/recon.yml
@@ -40,9 +40,7 @@ jobs:
 
       - name: 📜 Collect URLs from Gau for all alive subdomains
         run: |
-          mkdir -p "$OUTPUT_DIR/data"
-          cat "$OUTPUT_DIR/data/alive.txt" | gau --threads 5 --retry 3 --o "$OUTPUT_DIR/data/waybackurls.txt"
-
+          cat $OUTPUT_DIR/data/alive.txt | gau -t 5 -o $OUTPUT_DIR/data/waybackurls.txt || echo "gau failed"
 
       - name: 🔥 Run CORS Scanner (Corsy)
         run: |
